### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by nikkimishra** [mwisslead/vfp2py#2]
I am very new to Python so maybe the error I am getting could look silly and might have an obvious solution but I am struggling to solve it. I downloaded  the vfp2py-master zipped file and  extracted it in the Python folder in my c drive. Somehow managed to install the setup.py and now I am trying to run vfp2py where I get the below error:
  File "C:\Users\DPA524\AppData\Local\Programs\Python\Python37-32\vfp2py-master\vfp2py\__main__.py", line 7,
 in <module>
    from . import vfp2py
ImportError: attempted relative import with no known parent package

Please guide me.
Thank you.

**Comment by mwisslead** [comment]
Need to install vfp2py as a package and then run it with python -m vfp2py
