### ISSUE TITLE
`SET PROCEDURE TO` cannot be parsed

### ISSUE THREAD

**Issue by ted537** [mwisslead/vfp2py#7]
The expression `SET PROCEDURE TO` cannot be parsed by this library, though Visual FoxPro accepts it.

Relevant part of codebase: https://github.com/mwisslead/vfp2py/blob/4e18f95249ee92b36f66e4882909187061e3cb97/vfp2py/VisualFoxpro9.g4#L290

**Comment by mwisslead** [comment]
Fixed by https://github.com/mwisslead/vfp2py/commit/079023ea64a6104abde9cdd5a6d499e34f508179

Will be many examples of valid foxpro code that can't be parsed. If you find more, feel free to put in a pull request.
