### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by commodapse0q** [mwisslead/vfp2py#8]
Hi there! I'm currently trying to get this running on mac OS using terminal, Py3, and pip3, I got the following error below but was unsure exactly if this error is more a user error of software error, please let me know, thank you!

<img width="1025" alt="Screen Shot 2023-02-08 at 10 09 55 AM" src="https://user-images.githubusercontent.com/105806280/217570168-1f5863db-45f0-4aa1-9baa-2fd1fca18f3a.png">

**Comment by mwisslead** [comment]
I get the same output if I run the command you did but I don't think that is the recommended way to install python packages. I would recommend `pip install /path/to/vfp2py-master` or `python3 -m pip install /path/to/vfp2py-master`. You might also want to do `python3 -m pip install --user /path/to/vfp2py-master` and it will install in a user directory so you won't have to become root or have anything installed in a system directory.

Edited to change setup.py to vfp2py-master directory which is what pip expects.

**Comment by mwisslead** [comment]
I have added an updated version on pypi so you can just install from there with `pip install vfp2py`. I have changed the documentation to suggest that method of installation.

**Comment by commodapse0q** [comment]
Awesome, so that got it all installed properly. However, when I run I get hit with a few errors.

Once again this may be a user error issue on my side, but still like providing the feedback for development.

Let me know if you have any suggestions, and thanks for developing this!

<img width="1515" alt="Screen Shot 2023-02-09 at 9 20 53 AM" src="https://user-images.githubusercontent.com/105806280/217838430-689de222-d507-436f-96f2-66ecbbdf4654.png">

<img width="1515" alt="Screen Shot 2023-02-09 at 9 19 42 AM" src="https://user-images.githubusercontent.com/105806280/217838132-2e3fc513-502f-49c8-8902-f0e4b7e0f94a.png">

**Comment by commodapse0q** [comment]
I went ahead and used Homebrew to install unixodbc via `brew install unixodbc` and it resolved all those issues, assuming this was a user error on my part due to my lack of knowledge regarding paths.
